"""SYNTHETIC MARKETING SCIENCE DEMONSTRATION.

Everything in this package operates on **simulated** data generated by
``src.mmm.synthetic``. None of it is Square Enix data, and none of it touches
the real Kingdom Hearts IV community signals analysed elsewhere in this
project. There is no observed spend, price, promotion or sales data for an
unreleased game, so the marketing-science methods are demonstrated on a
dataset whose true parameters are known and recorded.

Because the data-generating process is known, the model can be judged on
whether it recovers it — which is the point of the lab.
"""

SYNTHETIC_NOTICE = (
    "SYNTHETIC MARKETING SCIENCE DEMONSTRATION — simulated data with known "
    "ground-truth parameters. This is not Square Enix data, and no quantity "
    "here describes actual commercial performance."
)

DATA_TYPE = "synthetic"

__all__ = ["DATA_TYPE", "SYNTHETIC_NOTICE"]
