"""Markdown report for the synthetic marketing science lab."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from src.mmm import SYNTHETIC_NOTICE

DISCLAIMER = (
    "> **SYNTHETIC MARKETING SCIENCE DEMONSTRATION.** Every figure in this "
    "report comes from simulated data generated by `src/mmm/synthetic.py`. "
    "**This is not Square Enix data.** No number here describes real media "
    "spend, real pricing, or real commercial performance, and none of it is "
    "derived from the Kingdom Hearts IV community signals analysed elsewhere "
    "in this project.\n"
)


def _fmt(value, digits: int = 2) -> str:
    if value is None:
        return "—"
    if isinstance(value, str):
        return value
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, (list, tuple)):
        return ", ".join(str(item) for item in value)
    if pd.isna(value):
        return "—"
    return f"{value:,.{digits}f}"


def write_mmm_report(
    fit,
    truth: dict,
    recovery: pd.DataFrame,
    notes: list,
    scenario: dict,
    metadata: dict,
    report_dir: Path,
) -> Path:
    """Render mmm_report.md from the fit's own generated results."""
    config = truth.get("config", {})
    lines = [
        "# Synthetic Bayesian Marketing Mix Model",
        "",
        DISCLAIMER,
        "",
        f"- Run: `{metadata['run_id']}` at {metadata['timestamp']}",
        f"- Git commit: `{metadata['git_commit']}`",
        f"- Generator seed: `{config.get('seed')}`",
        f"- Weeks simulated: {config.get('n_weeks')}",
        f"- Correlated channels: {config.get('correlated_channels')}",
        "",
        "## Why the data is synthetic",
        "",
        "Kingdom Hearts IV is unreleased, so no media spend, pricing, promotion "
        "or sales data exists for it. Inventing such figures and presenting them "
        "as observed would be dishonest. Simulating them from an explicit process "
        "makes the methods demonstrable and, more usefully, checkable: because "
        "the true parameters are known, the model can be scored on whether it "
        "recovers them.",
        "",
        "## Data-generating assumptions",
        "",
        "| Parameter | True value |",
        "|---|---|",
        f"| Baseline sales | {_fmt(config.get('baseline_sales'))} |",
        f"| Trend per week | {_fmt(config.get('trend_per_week'))} |",
        f"| Seasonality amplitude | {_fmt(config.get('seasonality_amplitude'))} |",
        f"| Price coefficient | {_fmt(config.get('price_coefficient'))} |",
        f"| Promotion lift | {_fmt(config.get('promotion_lift'))} |",
        f"| Event lift | {_fmt(config.get('event_lift'))} |",
        f"| Noise standard deviation | {_fmt(config.get('noise_sd'))} |",
        "",
        "| Channel | Base spend | True adstock decay | True Hill alpha | True half-saturation | True beta |",
        "|---|---|---|---|---|---|",
    ]
    for channel in config.get("channels", []):
        lines.append(
            f"| `{channel['name']}` | {_fmt(channel['base_spend'])} | "
            f"{_fmt(channel['adstock_decay'])} | {_fmt(channel['saturation_alpha'])} | "
            f"{_fmt(channel['saturation_theta'])} | {_fmt(channel['beta'])} |"
        )

    lines += [
        "",
        "## Model structure",
        "",
        "```",
        "simulated_sales_t = baseline + trend",
        "                    + sum_c beta_c * hill(adstock(spend_c))",
        "                    + price_coefficient * centred_price_t",
        "                    + promotion_coefficient * promotion_t",
        "                    + event_coefficient * event_t",
        "                    + seasonality + noise",
        "```",
        "",
        "Each channel's spend passes through geometric adstock (carryover) and "
        "Hill saturation (diminishing returns), with decay, curve shape and "
        "half-saturation point all estimated rather than fixed. Media "
        "coefficients are constrained non-negative.",
        "",
        "## Diagnostics",
        "",
        f"- Sampler: {fit.sampler['chains']} chains, {fit.sampler['draws']} draws, "
        f"{fit.sampler['tune']} tune, target_accept {fit.sampler['target_accept']}",
        f"- Max R-hat: {_fmt(fit.diagnostics.get('max_r_hat'), 4)}",
        f"- Minimum bulk ESS: {_fmt(fit.diagnostics.get('min_ess_bulk'), 0)}",
        f"- Divergences: {fit.diagnostics.get('divergences')}",
        f"- Converged: {fit.diagnostics.get('converged')}",
    ]
    for warning in fit.diagnostics.get("warnings", []):
        lines.append(f"  - Warning: {warning}")

    ppc = fit.posterior_predictive or {}
    if ppc:
        lines += [
            "",
            "Posterior predictive check: observed mean "
            f"{_fmt(ppc.get('observed_mean'))} against predicted "
            f"{_fmt(ppc.get('predicted_mean'))}; observed standard deviation "
            f"{_fmt(ppc.get('observed_std'))} against predicted "
            f"{_fmt(ppc.get('predicted_std'))}.",
        ]

    lines += [
        "",
        "## Channel contribution",
        "",
        "| Channel | Posterior mean | 5% | 95% | Share of simulated sales |",
        "|---|---|---|---|---|",
    ]
    for _, row in fit.contributions.iterrows():
        lines.append(
            f"| `{row['channel']}` | {_fmt(row['contribution_mean'], 0)} | "
            f"{_fmt(row['contribution_hdi_5'], 0)} | {_fmt(row['contribution_hdi_95'], 0)} | "
            f"{row['contribution_share_mean']:.1%} |"
        )

    true_contributions = truth.get("true_contributions", {})
    if true_contributions:
        lines += ["", "| Channel | True contribution |", "|---|---|"]
        for channel, value in true_contributions.items():
            lines.append(f"| `{channel}` | {_fmt(value, 0)} |")

    lines += [
        "",
        "## Recovery against known ground truth",
        "",
        "| Check | Passed | Estimated | Expected | What it tests |",
        "|---|---|---|---|---|",
    ]
    for _, row in recovery.iterrows():
        lines.append(
            f"| `{row['check']}` | {'yes' if row['passed'] else 'no'} | "
            f"{_fmt(row['estimated'])} | {_fmt(row['expected'])} | {row['detail']} |"
        )

    lines += ["", "## Identifiability limitations", ""]
    lines += [f"- {note}" for note in notes]

    if scenario:
        lines += [
            "",
            "## Scenario example",
            "",
            f"Plan: `{scenario['scenario']['label']}` "
            f"({scenario['scenario']['budget_changes']}).",
            "",
            "| Quantity | Value |",
            "|---|---|",
            f"| Baseline expected simulated sales | {_fmt(scenario['baseline_expected_sales'], 0)} |",
            f"| Scenario expected simulated sales | {_fmt(scenario['scenario_expected_sales'], 0)} |",
            f"| Difference (mean) | {_fmt(scenario['difference_mean'], 0)} |",
            f"| Difference ({int(scenario['interval_level'] * 100)}% interval) | "
            f"{_fmt(scenario['difference_lower'], 0)} to {_fmt(scenario['difference_upper'], 0)} |",
            f"| Probability of an increase | {scenario['probability_of_increase']:.0%} |",
            f"| Total spend change | {_fmt(scenario['spend_change'], 0)} |",
            "",
            "| Channel | Contribution change |",
            "|---|---|",
        ]
        for channel, change in scenario["channel_contribution_change"].items():
            lines.append(f"| `{channel}` | {_fmt(change, 0)} |")
        if scenario.get("warnings"):
            lines += ["", "Scenario warnings:", ""]
            lines += [f"- {warning}" for warning in scenario["warnings"]]

    lines += [
        "",
        "## What this does and does not show",
        "",
        "- It shows that adstock, saturation, price, promotion and event effects "
        "can be estimated jointly with uncertainty, and that the estimator "
        "recovers a known process.",
        "- It does **not** show causal media effectiveness. A fitted coefficient "
        "is an association within an assumed model; establishing causal effect "
        "needs experimentation such as geo tests or holdouts.",
        "- It does **not** describe Square Enix, Kingdom Hearts IV, or any real "
        "market. " + SYNTHETIC_NOTICE,
        "",
    ]

    path = Path(report_dir) / "mmm_report.md"
    path.write_text("\n".join(lines))
    return path
